name: deploy
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: macos-11.0
    steps:
      - uses: actions/checkout@v2
      - run: cargo run -- build
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./build